version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "${DB_PORT}:5432"

  odoo:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./addons:/mnt/extra-addons
      - odoo_data:/var/lib/odoo
      - odoo_logs:/var/log/odoo
    ports:
      - "8069:8069"
      
volumes:
  pgdata:
  odoo_data:
  odoo_logs: